# Generated by Django 4.1.5 on 2023-03-21 01:24

import backend.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billage',
            fields=[
                ('billage_id', models.CharField(default=backend.models.create_billage_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('billage_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('billage_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedBill',
            fields=[
                ('linked_bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('Electric', 'Electric'), ('Rent', 'Rent'), ('Gas', 'Gas'), ('Water', 'Water'), ('Television', 'Television'), ('Internet', 'Internet')], max_length=50)),
                ('bill_provider_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('billage_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.billage')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('payment_method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('bank_accoount', 'bank_account'), ('credit_card', 'credit_card')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_owner_firstname', models.CharField(max_length=25)),
                ('account_owner_lastname', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')])),
                ('exp_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}$', 'Date must be formatted as MM/YY')])),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('payment_method_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='UserBillDetailsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.linkedbill')),
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('bankaccount_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_owner_firstname', models.CharField(max_length=25)),
                ('account_owner_lastname', models.CharField(max_length=50)),
                ('bank_routing_nummber', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')])),
                ('bank_account_number', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator('^\\d+$', 'Only numbers are allowed')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('payment_method_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedBillSplit',
            fields=[
                ('linked_bill_split_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('bill_being_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.linkedbill')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillageBillActiveBill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bill_due_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('linked_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.linkedbill')),
            ],
        ),
    ]
