# Generated by Django 4.1.5 on 2023-03-21 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('bank_account', 'bank_account'), ('credit_card', 'credit_card')], max_length=20),
        ),
    ]
