# Generated by Django 4.1.5 on 2023-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkedbill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billagebill',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('canceled', 'canceled')], default='pending payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivebilldue',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('canceled', 'canceled')], default='pending payment', max_length=20),
        ),
    ]
