# Generated by Django 4.1.5 on 2023-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_billage_is_active_linkedbill_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedbill',
            name='bill_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Rent', 'Rent'), ('Gas', 'Gas'), ('Water', 'Water'), ('Cable', 'Cable'), ('Streaming', 'Streaming'), ('Internet', 'Internet'), ('Other', 'Other')], max_length=20),
        ),
    ]
