# Generated by Django 4.1.5 on 2023-03-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userbilldetailshistory_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod'),
        ),
    ]
