# Generated by Django 4.1.5 on 2023-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_linkedbill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmethod',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
