# Generated by Django 4.1.5 on 2023-03-21 02:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_delete_userbilldetailshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillDetailsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.linkedbill')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
