# Generated by Django 4.1.5 on 2023-03-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userbilldetailshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='bank_routing_nummber',
            new_name='bank_routing_number',
        ),
    ]
