# Generated by Django 4.1.6 on 2023-03-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0006_rename_bank_routing_nummber_userbankaccount_bank_routing_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="billage",
            name="billage_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
