# Generated by Django 4.1.6 on 2023-03-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_billage_billage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billage",
            name="billage_image",
            field=models.ImageField(default="villageicon.png", upload_to=""),
        ),
    ]
