# Generated by Django 4.1.5 on 2023-04-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_useractivebilldue_delete_useractivebilldueamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbilldetailshistory',
            old_name='due_date',
            new_name='bill_due_date',
        ),
        migrations.RenameField(
            model_name='userbilldetailshistory',
            old_name='amount_paid',
            new_name='due_amount',
        ),
        migrations.RenameField(
            model_name='userbilldetailshistory',
            old_name='bill_id',
            new_name='linked_bill',
        ),
        migrations.RenameField(
            model_name='userbilldetailshistory',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userbilldetailshistory',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='userbilldetailshistory',
            name='split_percentage',
        ),
        migrations.AddField(
            model_name='useractivebilldue',
            name='payment_method',
            field=models.ForeignKey(default='f7e02d45-4832-4e9a-b30f-8b450c744eb3', on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod'),
        ),
        migrations.AddField(
            model_name='userbilldetailshistory',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('failed payment', 'failed payment'), ('canceled', 'canceled')], max_length=50, null=True),
        ),
    ]
