# Generated by Django 4.1.5 on 2023-04-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_due_date_userbilldetailshistory_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivebilldue',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('failed payment', 'failed payment'), ('canceled', 'canceled')], max_length=50, null=True),
        ),
    ]
