# Generated by Django 4.1.5 on 2023-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_useractivebilldue_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billagebillactivebill',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('failed payment', 'failed payment'), ('canceled', 'canceled')], default='pending payment', max_length=50),
        ),
    ]
