# Generated by Django 4.1.5 on 2023-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_billagebillactivebill_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilldetailshistory',
            name='ate_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
