# Generated by Django 4.1.5 on 2023-04-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_ate_created_userbilldetailshistory_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billagebillactivebill',
            name='bill_status',
        ),
    ]
