# Generated by Django 4.1.5 on 2023-04-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0016_remove_billagebillactivebill_bill_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedbill',
            old_name='linked_bill_id',
            new_name='linked_bill',
        ),
        migrations.AlterField(
            model_name='linkedbillsplit',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='useractivebilldue',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='linked_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.linkedbill'),
        ),
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.userpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='userbilldetailshistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
