# Generated by Django 4.1.5 on 2023-04-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_linked_bill_id_linkedbill_linked_bill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillageBillActiveBill',
            new_name='BillageBill',
        ),
        migrations.AlterField(
            model_name='useractivebilldue',
            name='active_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.billage'),
        ),
    ]
