# Generated by Django 4.1.5 on 2023-04-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_billagebillactivebill_billagebill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivebilldue',
            name='active_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.billagebill'),
        ),
    ]
