# Generated by Django 4.1.5 on 2023-04-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_useractivebilldue_active_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbilldetailshistory',
            old_name='date_created',
            new_name='date_closed',
        ),
    ]
