# Generated by Django 4.1.5 on 2023-04-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_date_created_userbilldetailshistory_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billage',
            name='billage_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='linkedbill',
            name='bill_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Rent', 'Rent'), ('Gas', 'Gas'), ('Water', 'Water'), ('cable', 'cable'), ('streaming', 'streaming'), ('Internet', 'Internet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivebilldue',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('failed payment', 'failed payment'), ('canceled', 'canceled')], default='pending payment', max_length=20),
        ),
    ]
