# Generated by Django 4.2 on 2023-04-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_billage_billage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
                ('billage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.billage')),
            ],
        ),
    ]
