# Generated by Django 4.2 on 2023-04-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_invitelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteLink',
        ),
    ]
