# Generated by Django 4.1.5 on 2023-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_shareablelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='billagebill',
            name='bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending payment', 'pending payment'), ('failed payment', 'failed payment'), ('canceled', 'canceled')], default='pending payment', max_length=20),
        ),
    ]
