# Generated by Django 4.2 on 2023-04-15 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0026_billageadmins'),
    ]

    operations = [
        migrations.AddField(
            model_name='billage',
            name='billage_admins',
            field=models.ManyToManyField(related_name='administered_billages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BillageAdmins',
        ),
    ]
