# Generated by Django 4.1.5 on 2023-04-25 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_billage_billage_admins_delete_billageadmins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivebilldue',
            old_name='active_bill',
            new_name='billage_bill',
        ),
        migrations.AddField(
            model_name='userbilldetailshistory',
            name='billage_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.billagebill'),
        ),
    ]
